Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,17 +13,30 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Unzip project
-        run: unzip MinimalLauncher.zip -d project
-
-      - name: Setup Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: '17'
-
-      - name: Build APK
         run: |
-          cd project/MinimalLauncher
+          mkdir project
+          unzip MinimalLauncher.zip -d project
+          echo "=== After unzip ==="
+          ls -R project
+
+      - name: Find gradlew & build
+        run: |
+          cd project
+
+          # gradlew file locate karega automatically
+          GRADLEW_PATH=$(find . -type f -name "gradlew" | head -n 1)
+
+          echo "Found gradlew at: $GRADLEW_PATH"
+
+          if [ -z "$GRADLEW_PATH" ]; then
+            echo "❌ gradlew file not found"
+            exit 1
+          fi
+
+          # folder jaha gradlew hai waha jao
+          cd $(dirname "$GRADLEW_PATH")
+          
+
           chmod +x gradlew
           ./gradlew assembleDebug
 
@@ -31,4 +44,5 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: app-debug
-          path: project/MinimalLauncher/app/build/outputs/apk/debug/app-debug.apk
+          path: |
+            project/**/app/build/outputs/apk/debug/app-debug.apk
